sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t janekaxpo/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true janekaxpo/docker-react npm run test